# Generated by Django 3.2.7 on 2021-10-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211004_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayScraperResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('bid_format', models.CharField(blank=True, max_length=255, null=True)),
                ('comics_url', models.CharField(blank=True, max_length=255, null=True)),
                ('comics_img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('scraper_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.snipemodel')),
            ],
        ),
    ]
