# Generated by Django 3.2.7 on 2021-10-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ebayscraperresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipemodel',
            name='positive_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
