# Generated by Django 3.2.7 on 2021-10-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_snipemodel_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayscraperresult',
            name='is_already_in_gixen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ebayscraperresult',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
